### ISSUE TITLE
Automate cache uploading and signing via CI service account

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel.nix#25]
The cache `https://mitchmindtree-fuellabs.cachix.org` is currently generated and signed manually by @mitchmindtree. Ideally, this process should be automated via CI and signing should be done using a fuel service account key instead of a personal key.

**Comment by mitchmindtree** [comment]
Currently, both GitHub workflows have the necessary cache auth token and should automatically update the caches on each PR or nightly refresh.

That said, I agree it would be great for Fuel Labs to have its own `cachix` user and cache rather than rinse my personal one :smiling_face_with_tear:

I think cachix offers 5GB free for OSS projects which is probably plenty for what we currently have, but Fuel Labs having control would mean we could upgrade that if necessary, which we might want to do if we also want to start packaging the higher-level Fuel applications, indexer, and to to cache all recent packages for *all* supported platforms (currently we only do `x86_64-linux` and `x86_64-macos`).

**Comment by mitchmindtree** [comment]
Another option is self-hosting our own cache, which I think Nix makes pretty easy, but I don't have any experience with this just yet and cachix is just too easy.

**Comment by Voxelot** [comment]
This seems like something github should maybe support via registries: https://docs.github.com/en/packages/working-with-a-github-packages-registry

Opened a feature request here: https://github.com/orgs/community/discussions/34008

**Comment by mitchmindtree** [comment]
Adding this wiki entry on the topic of serving your own cache for reference: https://nixos.wiki/wiki/Binary_Cache
