### ISSUE TITLE
Caching binaries for aarch64-darwin (setup a self-hosted Apple ARM GitHub runner)

### ISSUE THREAD

**Issue by Br1ght0ne** [FuelLabs/fuel.nix#29]
Relevant resources: https://nixos.org/guides/cross-compilation.html
I think `crossSystem` argument set to `aarch64-darwin` running on a `macos-latest` runner should work.
sway repo has an example of building Rust packages (without Nix) for aarch64-darwin.

**Comment by mitchmindtree** [comment]
An attempt at the cross-compilation approach was made in #62, however it seems in order to enable the binary cache for Apple ARM device users we'll need to run the builds on an Apple ARM host too.

The new plan is to setup a self-hosted M1 runner for use until GitHub introduce ARM runners (slated for Q4). See the comments in #62 for more details.

**Comment by kayagokalp** [comment]
Closing this as we already have self hosted m1 runners in place now.
